ProjetoPR/projeto_pr/desafios/urls.py
from django.conf import settings
from django.conf.urls.static import static

from . import views
from django.urls import path

app_name = 'desafios'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login_user'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('logout/', views.log_out, name='logout'),
    path('user_homepage/', views.user_homepage, name='user_homepage'),
    path('<str:challenge_type>/create_challenge/', views.create_challenge, name='create_challenge'),
    path('<str:challenge_type>/challenges/', views.challenges_views, name='challenges'),
    path('<str:challenge_type>/challenges/like_up/', views.challenge_like_upvote, name='challenge_like_upvote'),
    path('<str:challenge_type>/challenges/like_down/', views.challenge_like_downvote, name='challenge_like_downvote'),
    path('challenges/<str:challenge_tag>/comments', views.comments, name='comments'),
    path('challenges/<str:challenge_tag>/post_comment', views.post_comment, name='post_comment'),

]

ProjetoPR/projeto_pr/projeto_pr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from desafios import views

urlpatterns = [
 url(r'^desafios/', include('desafios.urls')),
 url(r'^admin/', admin.site.urls),
 url(r'^accounts/login/', views.login_user),
]

ProjetoPR/projeto_pr/desafios/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.forms import User


class Challenge(models.Model):
    CHALLENGES_TYPES = (('programming', 'Programming Challenge'),
                        ('gaming', 'Gaming Challenge'),
                        ('sports', 'Sports Challenge'),
                        ('Culinary', 'Culinary Challenge'),
                        ('music', 'Music Challenge'),
                        ('makeup', 'MakeUp Challenge'))

    title = models.CharField(max_length=100)
    challenge_user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.CharField(max_length=15)
    content = models.CharField(max_length=1000, blank=True)
    image = models.URLField(blank=True, null=True)
    challenge_type = models.CharField(max_length=11, choices=CHALLENGES_TYPES)
    video = models.CharField(max_length=150, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    challenge_likes = models.ManyToManyField(User, related_name='like', blank=True)

    def get_title(self):
        return self.title

    def get_challenge_type(self):
        return self.challenge_type

    def get_tag(self):
        return self.tag

    def get_user(self):
        return self.challenge_user

    def get_content(self):
        return self.content

    def get_image(self):
        return self.image

    def get_video(self):
        return self.video

    def get_date(self):
        time = datetime.now()
        if self.date.minute == 0:
            return str(time.second - self.date.second) + "seg ago"
        elif (self.date.hour + 1) == time.hour and self.date.day == time.day:
            return str(time.minute - self.date.minute) + "min ago"
        elif self.date.day == time.day and self.date.month == time.month:
            if time.hour - (self.date.hour + 1) == 1:
                return str(time.hour - (self.date.hour + 1)) + " hour ago"
            return str(time.hour - (self.date.hour + 1)) + " hours ago"
        else:
            if self.date.month == time.month:
                if time.day - self.date.day == 1:
                    return str(time.day - self.date.day) + " day ago"
                return str(time.day - self.date.day) + " days ago"

        return self.date

    def get_challenge_likes(self):
        return self.challenge_likes.all().count()


class Comment(models.Model):
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    comment_challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, null=False)
    comment_likes = models.ManyToManyField(User, related_name='comment_like', blank=True)
    text = models.CharField(max_length=1000, blank=True)
    comment_date = models.DateTimeField(auto_now_add=True)

    def get_comment_user(self):
        return self.comment_user

    def get_comment_likes(self):
        return self.comment_likes.all().count()

    def get_text(self):
        return self.text

    def get_comment_date(self):
        time = datetime.now()
        if self.comment_date.minute == 0:
            return str(time.second - self.comment_date.second) + "seg ago"
        elif (self.comment_date.hour + 1) == time.hour and self.comment_date.day == time.day:
            return str(time.minute - self.comment_date.minute) + "min ago"
        elif self.comment_date.day == time.day and self.comment_date.month == time.month:
            if time.hour - (self.comment_date.hour + 1) == 1:
                return str(time.hour - (self.comment_date.hour + 1)) + " hour ago"
            return str(time.hour - (self.comment_date.hour + 1)) + " hours ago"
        else:
            if self.comment_date.month == time.month:
                if time.day - self.comment_date.day == 1:
                    return str(time.day - self.comment_date.day) + " day ago"
                return str(time.day - self.comment_date.day) + " days ago"

        return self.comment_date

ProjetoPR/projeto_pr/desafios/forms.py
from django import forms

class Upload_Image(forms.Form):
    image = forms.ImageField()

ProjetoPR/projeto_pr/desafios/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Count
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse, get_object_or_404
from django.contrib.auth.forms import User
from django.contrib import messages
from .models import Challenge, Comment
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


def index(request):
    return render(request, 'desafios/index.html')


@login_required(login_url="/accounts/login/")
def user_homepage(request):
    return render(request, 'desafios/user_homepage.html')


def sign_up(request):
    if request.method == 'POST':
        if request.POST['username']:
            username = request.POST['username']
        else:
            messages.info(request, 'Username field empty!')
            return redirect('desafios:sign_up')
        if request.POST['first_name']:
            first_name = request.POST['first_name']
        else:
            messages.info(request, 'First name field empty!')
            return redirect('desafios:sign_up')
        if request.POST['last_name']:
            last_name = request.POST['last_name']
        else:
            messages.info(request, 'Last name field empty!')
            return redirect('desafios:sign_up')
        if request.POST['email']:
            email = request.POST['email']
        else:
            messages.info(request, 'Email field empty!')
            return redirect('desafios:sign_up')
        if request.POST['password1']:
            password1 = request.POST['password1']
        else:
            messages.info(request, 'Password field empty!')
            return redirect('desafios:sign_up')
        if request.POST['password2']:
            password2 = request.POST['password2']
        else:
            messages.info(request, 'Password confirmation field empty!')
            return redirect('desafios:sign_up')
        if password1 == password2:
            if len(password1) < 5:
                messages.info(request, 'Password to small, must have 5 characters')
                return redirect('desafios:sign_up')
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username taken')
                return redirect('desafios:sign_up')
            if User.objects.filter(email=email).exists():
                messages.info(request, 'Email already exists')
                return redirect('desafios:sign_up')
            else:
                user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                                email=email, password=password1)
                user.save()
                new_user = authenticate(username=username, password=password1)
                login(request, new_user)
                return render(request, 'desafios/user_homepage.html')
        else:
            messages.info(request, 'Password is not matching')
            return redirect('desafios:sign_up')
    return render(request, 'desafios/signuppage.html')


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('desafios:user_homepage')
        else:
            messages.info(request, 'Username or Password incorrect')
    return render(request, 'desafios/loginpage.html')


@login_required(login_url="/accounts/login/")
def log_out(request):
    logout(request)
    return redirect('desafios:index')


@login_required(login_url="/accounts/login/")
def create_challenge(request, challenge_type):
    section = 0
    tag_text = 'challenge-{}'
    tag_text = tag_text.format(Challenge.objects.count())
    if request.GET['createbutton'] == 'image':
        section = 1
    elif request.GET['createbutton'] == 'link':
        section = 2
    if request.method == 'POST':
        title = request.POST['title1']
        content = request.POST['content']
        image = request.POST['image']
        if request.POST['video']:
            embed = request.POST['video']
            embed = embed.split("embed/")
            embed = embed[1].split(" frameborder")
            video = embed[0]
            video = video[:-1]
        else:
            video = None
        new_challenge = Challenge(title=title, content=content, challenge_type=challenge_type, tag=tag_text,
                                  image=image, video=video, challenge_user=request.user)
        new_challenge.save()
        return HttpResponseRedirect(reverse('desafios:challenges', args=(challenge_type,)))
    return render(request, 'desafios/create_challenge.html', {'section': section, 'challenge_type': challenge_type})


@login_required(login_url="/accounts/login/")
def challenges_views(request, challenge_type):
    challenge_type1 = str(challenge_type)
    challenge_list = Challenge.objects.filter(challenge_type__exact=challenge_type).order_by('date').reverse()
    x = 1
    if request.method == 'POST':
        if request.POST['order'] == 'top':
            x = 2
            challenge_list = Challenge.objects.filter(challenge_type__exact=challenge_type).annotate(likes_count=Count('challenge_likes')).order_by('-likes_count')
    return render(request, 'desafios/challenges.html',
                  {'challenge_type': challenge_type1, 'challenge_list': challenge_list, 'x': x})


@login_required(login_url="/accounts/login/")
def challenge_like_upvote(request, challenge_type):
    challenge = get_object_or_404(Challenge, id=request.POST.get('id'))
    if challenge.challenge_likes.filter(id=request.user.id).exists():
        pass
    else:
        challenge.challenge_likes.add(request.user)
    if request.is_ajax():
        y = 1
        challenge_likes = challenge.get_challenge_likes()
        return JsonResponse({'challenge_likes': challenge_likes, 'y': y})


@login_required(login_url="/accounts/login/")
def challenge_like_downvote(request, challenge_type):
    challenge = get_object_or_404(Challenge, id=request.POST.get('id'))
    challenge.challenge_likes.remove(request.user)
    if request.is_ajax():
        y = 2
        challenge_likes = challenge.get_challenge_likes()
        return JsonResponse({'challenge_likes': challenge_likes, 'y': y})


def comments(request, challenge_tag):
    challenge = Challenge.objects.filter(tag__exact=challenge_tag).get()
    challenge_comments = Comment.objects.filter(comment_challenge__exact=challenge.id).order_by('comment_date').reverse()
    return render(request, 'desafios/comments.html', {'challenge': challenge, 'comments': challenge_comments})


def post_comment(request, challenge_tag):
    if request.method == 'POST':
        challenge = Challenge.objects.filter(tag__exact=challenge_tag).get()
        new_comment = Comment(comment_user=request.user, comment_challenge=challenge, text=request.POST['content'])
        new_comment.save()
        return HttpResponseRedirect(reverse('desafios:comments', args=(challenge_tag,)))

ProjetoPR/projeto_pr/desafios/templates/desafios/challenges.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'desafios/challenges.css' %}" />
    <link rel="stylesheet" href="{% static 'desafios/all.min.css' %}" />
    <title>Programming Challenges</title>
</head>
<body>
    <header id="header" class="alt">
        <a href="{% url 'desafios:user_homepage' %}" class="logo"><strong>Entretain</strong> <span>US</span></a>
       <!-- <a href="{% url 'desafios:index' %}" class="logo return"><strong>Return to Challenges</strong></a>-->
        <a href="{% url 'desafios:logout' %}" class="logo"><strong>Logout</strong></a>
    </header>
    <div class="main">
        <section>
            <div>
                <h1 class="challenge_type">
                    {{ challenge_type.upper }} CHALLENGES
                </h1>
            </div>
            <div class="createpost">
                <form action="{% url 'desafios:create_challenge' challenge_type %}">
                    <input type="submit" id="1" class="postbutton" value="Create Post" name="createbutton">
                </form>
                <div class="icon">
                    <form action="{% url 'desafios:create_challenge' challenge_type %}">
                        <button class="btn" id="2" name="createbutton" value="image"><i class="fas fa-image fa-2x"></i></button>
                    </form>
                </div>
                <div class="icon">
                    <form action="{% url 'desafios:create_challenge' challenge_type %}">
                        <button class="btn" id="3" name="createbutton" value="link"><i class="fas fa-link fa-2x"></i></button>
                    </form>
                </div>
            </div>
            <div class="orderbar">
                <form action="{% url 'desafios:challenges' challenge_type %}" method="post">
                    {% csrf_token %}
                    <div class="a1">
                        <p class="new">
                            <button class="icons i1" id="parent_div1" type="submit" name="order" value="date">
                                <i class="fas fa-certificate fa-lg" id="child_div_1"></i> New
                            </button>
                        </p>
                    </div>
                </form>
                <form action="{% url 'desafios:challenges' challenge_type %}" method="post">
                    {% csrf_token %}
                    <div class="a1">
                        <p class="new">
                            <button class="icons i2" name="order" value="top" id="parent_div2" type="submit">
                                <i class="fas fa-arrow-up" id="child_div_2"></i> Top
                            </button>
                            {% if x == 2 %}
                                <script>
                                    document.getElementById("parent_div2").style.backgroundColor = "rgb(232, 232, 232)";
                                    document.getElementById("parent_div2").style.borderRadius = "20px";
                                    document.getElementById("parent_div2").style.color = "rgb(50, 147, 219)";
                                    document.getElementById("child_div_2").style.color = "rgb(50, 147, 219)"
                                </script>
                                {% else %}
                                    <script>
                                        document.getElementById("parent_div1").style.backgroundColor = "rgb(232, 232, 232)";
                                        document.getElementById("parent_div1").style.borderRadius = "20px";
                                        document.getElementById("parent_div1").style.color = "rgb(50, 147, 219)";
                                        document.getElementById("child_div_1").style.color = "rgb(50, 147, 219)"
                                    </script>
                            {% endif %}
                        </p>
                    </div>
                </form>
            </div>
                {% for challenge in challenge_list %}
                    <div class="posts">
                        <div class="upvotes">
                            <div  class="challenge-likes" id="parent_div">
                                <p class="upvt">
                                    <form action="{% url 'desafios:challenge_like_upvote' challenge_type %}" method="post">
                                        {%  csrf_token %}
                                        <button class="v up" type="submit" value="{{ challenge.id }}"  name="like" id="5" >
                                            <div class="v1" id="parent_div2"><i class="far fa-arrow-alt-circle-up" id="child_div_3"></i></div>
                                        </button>
                                    </form>
                                    <p class="n-likes" id="challenge-likes{{ challenge.id }}" >{{ challenge.get_challenge_likes }}</p>
                                    <form action="{% url 'desafios:challenge_like_downvote' challenge_type %}" method="post">
                                    {%  csrf_token %}
                                        <button class="v down" type="submit" value="{{ challenge.id }}"  name="like" id="6" >
                                            <div class="v1" id="parent_div2"><i class="far fa-arrow-alt-circle-down" id="child_div_4"></i></div>
                                        </button>
                                    </form>
                                </p>
                            </div>
                        </div>
                        <div class="bigdiv">
                            <div class="poster">
                                <p class="author" id="author">Posted by {{ challenge.get_user }}<ul><li><span>{{ challenge.get_date }}</span></li></ul></p>
                            </div>
                            <div class="postcontent">
                                <p class="posttitle">{{ challenge.get_title }}</p>
                                {% if challenge.get_content %}
                                    <p class="textcontent">{{ challenge.get_content }}</p>
                                {% endif %}
                                {% if challenge.get_image %}
                                    <img src='{{ challenge.get_image }}'style="max-height: 632.05px; max-width: 430px" >
                                {% endif %}
                                {% if challenge.get_video %}
                                    <div class="postvideo">
                                        <iframe class="video" width="609.9" height="315" src="https://www.youtube.com/embed/{{ challenge.get_video }}"
                                                frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                                allowfullscreen>
                                        </iframe>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="postcomment">
                                <div class="commentdiv" id="">
                                    <p class="comments">
                                        <form action="{% url 'desafios:comments' challenge.get_tag %}">
                                            <button class="commentbutton"><i class="fas fa-comment"></i> Comments
                                            </button>
                                        </form>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        </section>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function (event) {
            $(document).on('click', '#5', function (event) {
                event.preventDefault();
                const pk=$(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url:'{% url 'desafios:challenge_like_upvote' challenge_type %}',
                    data: {id:pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success:function (response) {
                        console.log($('#challenge-likes'+pk).text(`${response['challenge_likes']}`));
                    },
                    error:function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function (event) {
            $(document).on('click', '#6', function (event) {
                event.preventDefault();
                const pk=$(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url:'{% url 'desafios:challenge_like_downvote' challenge_type %}',
                    data: {id:pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success:function (response) {
                        console.log($('#challenge-likes'+pk).text(`${response['challenge_likes']}`));
                    },
                    error:function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
        });
    </script>
    <!--<script>
        function set_time(date) {
            var date_now = new Date.now();
            document.getElementById('author').innerText=date_now.toString();

        }
    </script>-->
</body>
</html>

ProjetoPR/projeto_pr/desafios/templates/desafios/comments.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'desafios/comments.css' %}" />
    <link rel="stylesheet" href="{% static 'desafios/all.min.css' %}" />
    <title>Comments Section</title>
</head>
<body>
    <header id="header" class="alt">
        <a href="{% url 'desafios:user_homepage' %}" class="logo"><strong>Entretain</strong> <span>US</span></a>
        <a href="{% url 'desafios:challenges' challenge.challenge_type %}" class="logo"><strong>Return to Challenge</strong></a>
        <a href="{% url 'desafios:logout' %}" class="logo"><strong>Logout</strong></a>
    </header>
    <div class="main">
        <div class="commentbox">
            <div class="upvtbar">
                <div  class="challenge-likes" id="parent_div">
                    <p class="upvt">
                        <form action="{% url 'desafios:challenge_like_upvote' challenge.challenge_type %}" method="post">
                            {%  csrf_token %}
                            <button class="v up" type="submit" value="{{ challenge.id }}"  name="like" id="5" >
                                <div class="v1" id="parent_div2"><i class="far fa-arrow-alt-circle-up" id="child_div_3"></i></div>
                            </button>
                        </form>
                        <p class="n-likes" id="challenge-likes{{ challenge.id }}" >{{ challenge.get_challenge_likes }}</p>
                        <form action="{% url 'desafios:challenge_like_downvote' challenge.challenge_type %}" method="post">
                            {%  csrf_token %}
                            <button class="v down" type="submit" value="{{ challenge.id }}"  name="like" id="6" >
                                <div class="v1" id="parent_div2"><i class="far fa-arrow-alt-circle-down" id="child_div_4"></i></div>
                            </button>
                        </form>
                    </p>
                </div>
            </div>
            <div class="contentbox">
                <div class="poster">
                    <p class="author" id="author">Posted by {{ challenge.get_user }}<ul><li><span>{{ challenge.get_date }}</span></li></ul></p>
                </div>
                <div class="content">
                    <p class="posttitle">{{ challenge.get_title }}</p>
                    {% if challenge.get_content %}
                        <p class="textcontent">{{ challenge.get_content }}</p>
                    {% endif %}
                    {% if challenge.get_image %}
                        <img src='{{ challenge.get_image }}'style="max-height: 632.05px; max-width: 430px" >
                    {% endif %}
                    {% if challenge.get_video %}
                        <div class="postvideo">
                            <iframe class="video" width="609.9" height="315" src="https://www.youtube.com/embed/{{ challenge.get_video }}"
                                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen>
                            </iframe>
                        </div>
                    {% endif %}
                </div>
                <form action="{% url 'desafios:post_comment' challenge.get_tag %}" method="post">
                    {%  csrf_token %}
                    <div class="textareabox">
                        <p class="commenter">Comment as {{ user.get_username }}</p>
                            <textarea class="areaP" name="content" id="content" placeholder="What are your thoughts"></textarea>
                    </div>
                    <div class="Post">
                        <button class="commentbutton">Comment</button>
                    </div>
                    <hr>
                </form>
                <div class="allcomment">
                    {% for comment in comments %}
                        <div class="comment1">
                            <div class="commentuser">
                                <p class="user&time">{{ comment.get_comment_user }}<ul><li><span>{{ comment.get_comment_date }}</span></li></ul></p>
                            </div>
                            <div>
                                <p class="commenttext">{{ comment.get_text }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script>
       /* let btnarrowup = document.querySelector('#child_div_3');
        let btnarrowdown= document.querySelector('#child_div_4');

            btnarrowup.addEventListener('click', () => btnarrowup.style.color = 'rgb(50, 147, 219');
            btnarrowdown.addEventListener('click', () => btnarrowdown.style.color = 'red');
        */
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function (event) {
            $(document).on('click', '#5', function (event) {
                event.preventDefault();
                const pk=$(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url:'{% url 'desafios:challenge_like_upvote' challenge.challenge_type %}',
                    data: {id:pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success:function (response) {
                        console.log($('#challenge-likes'+pk).text(`${response['challenge_likes']}`));
                    },
                    error:function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function (event) {
            $(document).on('click', '#6', function (event) {
                event.preventDefault();
                const pk=$(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url:'{% url 'desafios:challenge_like_downvote' challenge.challenge_type %}',
                    data: {id:pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success:function (response) {
                        console.log($('#challenge-likes'+pk).text(`${response['challenge_likes']}`));
                    },
                    error:function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
        });
    </script>
</body>
</html>

ProjetoPR/projeto_pr/desafios/templates/desafios/user_homepage.html
{% extends "desafios/index.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block menu %}
        <!-- Menu -->
            <div class="logout">
                <a href="{% url 'desafios:logout' %}" class="logo logout"><strong>Logout</strong></a>
            </div>
        </nav>
    {% endblock %}

    {% block welcome %}
        <h1>Welcome {{ user.get_username }}</h1>
    {% endblock %}
</body>
</html>